#spring:
##  数据源配置
#  datasource:
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    username: root
#  profiles:
#    active: dev
#  # 服务名
#  application:
#    name: gulimall-product
#  # 服务发现
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
## 端口号
#server:
#  port: 9010
#mybatis-plus:
#  # 默认扫描mapper包
#  mapper-locations: classpath:**/mapper/**/*.xml
#  # Mybatis-Plus日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: auto
mybatis-plus:
  global-config:
    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    # debug在该路径下日志
    com.qx.gulimall: error
spring:
  cloud:
    alicloud:
      access-key: LTAI4G6sLYD3UTuX1NkAbbWx
      secret-key: NrrUFkrQAAUmnmQvjsClwXZD8HpAG7
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  # 将返回前端的数据格式化为当前形式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    ## 开启缓存
    cache: false
  ## redis配置
  redis:
    host: 192.168.56.10
  # 指定cache缓存使用redis
  cache:
    type: redis
    redis:
      # 防止缓存穿透
      cache-null-values: true
      # 设置缓存过期时间
      time-to-live: 3600000